# Generated by Django 5.1.5 on 2026-01-15 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_admin_systemsettings_activitylog_announcement_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('achievement_type', models.CharField(choices=[('streak', 'Streak Achievement'), ('completion', 'Course Completion'), ('quiz_master', 'Quiz Master'), ('time_spent', 'Time Spent'), ('first_steps', 'First Steps'), ('social', 'Social Achievement')], max_length=20)),
                ('requirement_value', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '36. Achievements',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('featured_img', models.ImageField(blank=True, null=True, upload_to='learning_paths/')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_hours', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.coursecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '33. Learning Paths',
            },
        ),
        migrations.CreateModel(
            name='LearningStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('total_learning_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streak', to='main.student')),
            ],
            options={
                'verbose_name_plural': '28. Learning Streaks',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('achievement', 'Achievement Unlocked'), ('course', 'Course Update'), ('assignment', 'New Assignment'), ('reminder', 'Study Reminder'), ('system', 'System Notification'), ('streak', 'Streak Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.student')),
            ],
            options={
                'verbose_name_plural': '38. Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('lessons', 'Complete Lessons'), ('minutes', 'Study Minutes'), ('courses', 'Complete Courses'), ('quizzes', 'Pass Quizzes')], default='lessons', max_length=20)),
                ('target_value', models.IntegerField(default=5)),
                ('current_value', models.IntegerField(default=0)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to='main.student')),
            ],
            options={
                'verbose_name_plural': '29. Weekly Goals',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_chapters', models.IntegerField(default=0)),
                ('completed_chapters', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('total_time_spent_seconds', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course_progress', to='main.course')),
                ('enrollment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='main.studentcourseenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='main.student')),
            ],
            options={
                'verbose_name_plural': '31. Course Progress',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='DailyLearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('quizzes_attempted', models.IntegerField(default=0)),
                ('courses_accessed', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='main.student')),
            ],
            options={
                'verbose_name_plural': '32. Daily Learning Activities',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LearningPathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='main.course')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_courses', to='main.learningpath')),
            ],
            options={
                'verbose_name_plural': '34. Learning Path Courses',
                'ordering': ['order'],
                'unique_together': {('learning_path', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('last_position_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='main.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='main.student')),
            ],
            options={
                'verbose_name_plural': '30. Lesson Progress',
                'unique_together': {('student', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='main.achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='main.student')),
            ],
            options={
                'verbose_name_plural': '37. Student Achievements',
                'unique_together': {('student', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='StudentLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('courses_completed', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='main.learningpath')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_paths', to='main.student')),
            ],
            options={
                'verbose_name_plural': '35. Student Learning Paths',
                'unique_together': {('student', 'learning_path')},
            },
        ),
    ]
