# Generated by Django 5.1.5 on 2026-01-15 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_achievement_learningpath_learningstreak_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('featured_img', models.ImageField(blank=True, null=True, upload_to='lesson_imgs/')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('module_count', models.IntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='main.coursecategory')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '42. Lessons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_to_all', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.lesson')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_lessons', to='main.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '44. Lesson Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF Document'), ('image', 'Image'), ('other', 'Other')], default='video', max_length=20)),
                ('file', models.FileField(upload_to='lesson_materials/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.lesson')),
            ],
            options={
                'verbose_name_plural': '43. Lesson Materials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeacherActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('lesson_completed', 'Completed Lesson'), ('assignment_submitted', 'Submitted Assignment'), ('course_started', 'Started Course'), ('comment_added', 'Added Comment'), ('quiz_completed', 'Completed Quiz'), ('material_downloaded', 'Downloaded Material'), ('session_attended', 'Attended Session')], max_length=30)),
                ('target_name', models.CharField(max_length=200)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_activities', to='main.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_feed', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '41. Teacher Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherDashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('active_lessons', models.IntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('students_change_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('lessons_change_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completion_change_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '45. Teacher Dashboard Metrics',
            },
        ),
        migrations.CreateModel(
            name='TeacherSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='main.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '40. Teacher Sessions',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('piano', 'Piano'), ('guitar', 'Guitar'), ('violin', 'Violin'), ('voice', 'Voice'), ('drums', 'Drums'), ('flute', 'Flute'), ('saxophone', 'Saxophone'), ('other', 'Other')], default='piano', max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('warning', 'Warning')], default='active', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='main.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '39. Teacher Students',
                'ordering': ['-last_active'],
                'unique_together': {('teacher', 'student')},
            },
        ),
    ]
