# Generated by Django 4.2.10 on 2026-01-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_chapter_options_chapter_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='LessonAssignment',
        ),
        migrations.DeleteModel(
            name='StudentAssignment',
        ),
    ]
