# Generated by Django 5.1.5 on 2026-01-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_remove_assignment_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherStudentChat',
        ),
    ]
