# Generated by Django 4.2.10 on 2026-01-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_message_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
