# Generated by Django 5.1.5 on 2026-01-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_remove_announcement_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
