# Generated by Django 5.1.5 on 2026-01-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_report_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
