# Generated by Django 5.1.5 on 2026-01-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_remove_notification_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningStreak',
        ),
    ]
