# Generated by Django 5.1.5 on 2026-01-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_remove_learning_streak_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('completion', 'Course Completion'), ('quiz_master', 'Quiz Master'), ('time_spent', 'Time Spent'), ('first_steps', 'First Steps'), ('social', 'Social Achievement')], max_length=20),
        ),
    ]
