# Generated by Django 5.1.5 on 2026-01-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_add_lesson_objectives_downloadables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lessons_per_month', models.IntegerField()),
                ('max_teachers', models.IntegerField(default=1)),
                ('features', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '23. Subscription Plans',
            },
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='category',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studentlearningpath',
            name='learning_path',
        ),
        migrations.RemoveField(
            model_name='learningpathcourse',
            name='learning_path',
        ),
        migrations.AlterUniqueTogether(
            name='learningpathcourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='learningpathcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='studentlearningpath',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentlearningpath',
            name='student',
        ),
        migrations.AlterField(
            model_name='teacheractivity',
            name='activity_type',
            field=models.CharField(choices=[('lesson_completed', 'Completed Lesson'), ('assignment_submitted', 'Submitted Assignment'), ('course_started', 'Started Course'), ('comment_added', 'Added Comment'), ('material_downloaded', 'Downloaded Material'), ('session_attended', 'Attended Session')], max_length=30),
        ),
        migrations.DeleteModel(
            name='AttemptQuiz',
        ),
        migrations.DeleteModel(
            name='CourseQuiz',
        ),
        migrations.DeleteModel(
            name='LearningPath',
        ),
        migrations.DeleteModel(
            name='LearningPathCourse',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizQuestions',
        ),
        migrations.DeleteModel(
            name='StudentLearningPath',
        ),
    ]
