# Generated by Django 5.1.5 on 2026-01-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_subscriptionplan_remove_coursequiz_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
