# Generated by Django 5.1.5 on 2026-01-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_subscriptionplan_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='lessons_per_week',
            field=models.IntegerField(blank=True, help_text='Max lessons per week (None = unlimited)', null=True),
        ),
    ]
