# Generated by Django 5.1.5 on 2026-01-29 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_create_subscription_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.subscription'),
            preserve_default=False,
        ),
    ]
