# Generated by Django 5.1.5 on 2026-02-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_access_control_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='modulelesson',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='can_access_premium_content',
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lessons_used_this_month',
            field=models.IntegerField(default=0),
        ),
    ]
