# Generated by Django 5.1.5 on 2026-02-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_remove_course_is_premium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('course_view', 'Course View'), ('lesson_view', 'Lesson View'), ('course_enroll', 'Course Enrollment'), ('course_unenroll', 'Course Unenrollment'), ('download_material', 'Download Material'), ('lesson_complete', 'Lesson Complete')], max_length=30)),
                ('was_allowed', models.BooleanField(default=True)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs_admin', to='main.admin')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='main.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='main.modulelesson')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs_student', to='main.student')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='main.subscription')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs_teacher', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '55. Access Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='main_access_created_6c755c_idx'), models.Index(fields=['access_type'], name='main_access_access__80ce81_idx'), models.Index(fields=['was_allowed'], name='main_access_was_all_3451b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('payment_type', models.CharField(choices=[('subscription_purchase', 'Subscription Purchase'), ('plan_upgrade', 'Plan Upgrade'), ('plan_downgrade', 'Plan Downgrade'), ('renewal', 'Renewal'), ('refund', 'Refund'), ('failed_attempt', 'Failed Attempt')], max_length=30)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('wallet', 'Wallet'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='main.student')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='main.subscription')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='main.subscriptionplan')),
            ],
            options={
                'verbose_name_plural': '54. Payment Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='main_paymen_created_9eca2d_idx'), models.Index(fields=['status'], name='main_paymen_status_6b585f_idx'), models.Index(fields=['payment_type'], name='main_paymen_payment_b8809c_idx'), models.Index(fields=['transaction_id'], name='main_paymen_transac_af0a27_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('upload_type', models.CharField(choices=[('lesson_content', 'Lesson Content'), ('student_submission', 'Student Submission'), ('profile_image', 'Profile Image'), ('course_image', 'Course Image'), ('study_material', 'Study Material'), ('downloadable_resource', 'Downloadable Resource'), ('other', 'Other')], max_length=30)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_logs', to='main.admin')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_logs', to='main.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_logs', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '53. Upload Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='main_upload_created_4eb82b_idx'), models.Index(fields=['upload_type'], name='main_upload_upload__f23034_idx'), models.Index(fields=['status'], name='main_upload_status_69ca3e_idx')],
            },
        ),
    ]
