# Generated by Django 5.1.5 on 2026-02-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_add_audit_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulelesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_content/'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='contact_email',
            field=models.EmailField(default='admin@sonaramusicacademy.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='site_name',
            field=models.CharField(default='Sonara Music Academy', max_length=200),
        ),
    ]
