# Generated by Django 5.1.5 on 2026-02-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_modulelesson_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulelesson',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='lesson_content/'),
        ),
    ]
