# Generated by Django 5.1.5 on 2026-02-11 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_alter_modulelesson_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulelesson',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Mark as premium content'),
        ),
        migrations.AddField(
            model_name='teacherstudent',
            name='lessons_assigned_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='face_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='insta_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='twit_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='web_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='you_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, help_text='e.g. Mon/Wed 4:00 PM', max_length=200, null=True)),
                ('max_students', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_classes', to='main.school')),
            ],
            options={
                'verbose_name_plural': '57. Group Classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('individual', 'Individual Student'), ('group', 'Group Class')], default='individual', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('group_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='main.groupclass')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_assignments', to='main.modulelesson')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='main.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_lesson_assignments', to='main.student')),
            ],
            options={
                'verbose_name_plural': '60. Lesson Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_user', to='main.school')),
            ],
            options={
                'verbose_name_plural': '56. School Users',
            },
        ),
        migrations.CreateModel(
            name='GroupClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('group_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='main.groupclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='main.student')),
            ],
            options={
                'verbose_name_plural': '59. Group Class Students',
                'unique_together': {('group_class', 'student')},
            },
        ),
        migrations.CreateModel(
            name='GroupClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('group_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_teachers', to='main.groupclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_teaching', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '58. Group Class Teachers',
                'unique_together': {('group_class', 'teacher')},
            },
        ),
    ]
